from __future__ import annotations

import pandas as pd


def assign_risk_tier(probability: float) -> str:
    """Map predicted probability to an operational risk tier."""

    if not 0 <= probability <= 1:
        raise ValueError(
            f"Probability must be between 0 and 1: {probability}"
        )

    if probability < 0.20:
        return "LOW"

    if probability < 0.40:
        return "MEDIUM"

    if probability < 0.70:
        return "HIGH"

    return "CRITICAL"


def assign_action_priority(risk_tier: str) -> str:
    """Map risk tier to an operational review priority."""

    priorities = {
        "LOW": "ROUTINE",
        "MEDIUM": "MONITOR",
        "HIGH": "REVIEW",
        "CRITICAL": "IMMEDIATE_REVIEW",
    }

    if risk_tier not in priorities:
        raise ValueError(
            f"Unknown risk tier: {risk_tier}"
        )

    return priorities[risk_tier]


def build_risk_intelligence_output(
    risk_evidence: pd.DataFrame,
) -> pd.DataFrame:
    """
    Build decision-ready loan-level risk intelligence.

    The input must already contain model predictions and
    transparent evidence generated by the previous layer.
    """

    required_columns = {
        "loan_id",
        "reporting_month",
        "predicted_probability",
        "risk_flag",
        "threshold",
        "risk_evidence",
        "evidence_count",
        "evidence_category",
    }

    missing = required_columns - set(risk_evidence.columns)

    if missing:
        raise ValueError(
            f"Missing required columns: {sorted(missing)}"
        )

    result = risk_evidence.copy()

    result["risk_tier"] = result[
        "predicted_probability"
    ].apply(assign_risk_tier)

    result["action_priority"] = result[
        "risk_tier"
    ].apply(assign_action_priority)

    return result[
        [
            "loan_id",
            "reporting_month",
            "predicted_probability",
            "risk_flag",
            "threshold",
            "risk_tier",
            "action_priority",
            "risk_evidence",
            "evidence_count",
            "evidence_category",
        ]
    ]